name: Update IPTV Source
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:  # ⬅️ 必须添加这一段权限声明
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 显式传入令牌

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run processor
        run: python iptv_processor.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add hebei_iptv.m3u
          git commit -m "Auto update IPTV source" || exit 0
          git push
